
export const FETCH_HOMEPAGE_CATEGORIES = "FETCH_HOMEPAGE_CATEGORIES";
export const FETCH_HP_CATEGORIES_SUCCESS = "FETCH_HP_CATEGORIES_SUCCESS";
export const HP_CAT_RETRIEVED = "HP_CAT_RETRIEVED";
export const HP_CAT_IS_LOADING = "HP_CAT_IS_LOADING";
export const HP_LOADING_HAS_ERRORED = "HP_LOADING_HAS_ERRORED";
